# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Java CI

on:
  push:
    branches:
      - main
      - jenk
  workflow_dispatch:    
  
jobs:
  java_jobs:

    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'      
    - uses: actions/checkout@v3
    - name: Show java versions
      run: 'java -version'
    - name: install dependencies
      run: 'mvn compile'
      
    - run: 'mvn package -DskipTests'
    - name: Testing
      run: 'mvn test'
